import {
  AmazonImage,
  BigCommerceImage,
  CDiscountImage,
  EbayImage,
  EtsyImage,
  MagentoImage,
  NOTHSImage,
  PrestoShopImage,
  PriceMinisterImage,
  RakutenImage,
  ShopifyImage,
  VendImage,
  WalmartImage,
  WooCommerceImage,
  SquareSpaceImage,
  DarkAmazonImage,
  DarkEbayImage,
  DarkShopifyImage,
  DarkBigcommerceImage,
  DarkEtsyImage,
  DarkMagentoImage,
  DarkWoocommerceImage,
  DarkSquareSpaceImage,
} from '../../../../../assets/images';
import { AppRoutes } from '../../../../app/api';

import { WelcomeStoreProps } from '../../components/WelcomeStore';

export const getStores = (isDark: boolean): WelcomeStoreProps[] => [
  {
    name: 'Amazon',
    image: isDark ? DarkAmazonImage : AmazonImage,
    imageHeight: 14,
    imageWidth: 50,
    path: '#',
  },
  {
    name: 'Ebay',
    image: isDark ? DarkEbayImage : EbayImage,
    imageHeight: 18,
    imageWidth: 45,
    path: AppRoutes.Auth.Welcome.Step1.EBay,
  },
  {
    name: 'Shopify',
    image: isDark ? DarkShopifyImage : ShopifyImage,
    imageHeight: 18,
    imageWidth: 63,
    path: AppRoutes.Auth.Welcome.Step1.Shopify,
  },
  // {
  //   image: CDiscountImage,
  //   imageHeight: 10,
  //   imageWidth: 64,
  //   path: '#',
  // },
  {
    name: 'BigCommerce',
    image: isDark ? DarkBigcommerceImage : BigCommerceImage,
    imageHeight: 16,
    imageWidth: 70,
    path: AppRoutes.Auth.Welcome.Step1.BigCommerce,
  },
  {
    name: 'Etsy',
    image: isDark ? DarkEtsyImage : EtsyImage,
    imageHeight: 14,
    imageWidth: 30,
    path: AppRoutes.Auth.Welcome.Step1.Etsy,
  },
  // {
  //   image: PriceMinisterImage,
  //   imageHeight: 8,
  //   imageWidth: 68,
  //   path: '#',
  // },
  // {
  //   image: RakutenImage,
  //   imageHeight: 14,
  //   imageWidth: 47,
  //   path: '#',
  // },
  // {
  //   image: VendImage,
  //   imageHeight: 18,
  //   imageWidth: 42,
  //   path: '#',
  // },
  // {
  //   image: NOTHSImage,
  //   imageHeight: 20,
  //   imageWidth: 44,
  //   path: '#',
  // },
  {
    name: 'Magento',
    image: isDark ? DarkMagentoImage : MagentoImage,
    imageHeight: 18,
    imageWidth: 62,
    path: AppRoutes.Auth.Welcome.Step1.Magento2,
  },
  {
    name: 'WooCommerce',
    image: isDark ? DarkWoocommerceImage : WooCommerceImage,
    imageHeight: 14,
    imageWidth: 69,
    path: AppRoutes.Auth.Welcome.Step1.WooCommerce,
  },
  {
    name: 'Squarespace',
    image: isDark ? DarkSquareSpaceImage : SquareSpaceImage,
    imageHeight: 44,
    imageWidth: 69,
    path: AppRoutes.Auth.Welcome.Step1.SquareSpace,
  },
  // {
  //   image: PrestoShopImage,
  //   imageHeight: 12,
  //   imageWidth: 72,
  //   path: '#',
  // },
  // {
  //   image: WalmartImage,
  //   imageHeight: 18,
  //   imageWidth: 76,
  //   path: '#',
  // },
];
