FROM node:12.15.0 AS builder

WORKDIR /app

COPY . .

RUN NODE_OPTIONS="--max-old-space-size=8192" yarn build

FROM nginx:alpine

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html
COPY --from=builder /app/build .

CMD ["nginx", "-g", "daemon off;"]
